name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  install-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: install-deps

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Run lint
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    needs: install-deps

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Run test
        run: pnpm run test
